### PR TITLE
Build refactoring

### PR DESCRIPTION
**Pull request by SukantPal**
# Synopsis 📃 

This change will modernize pixi-tilemap's codebase to be up-to-date with the latest PixiJS standards 😃! I've done the following changes:

* `types.d.ts`: This declares `@pixi/<packages>` modules and whatever classes pixi-tilemaps takes from those packages. This is necessary b/c only `pixi.js` has typings, but we import classes from `@pixi/*` packages.

* `import/export`: The ES6 import/export syntax makes things modular & allows us to build to UMD & ESM bundles.

* `api-extractor`: Automated declaration file generation!

* `rollup`: This allows us to generate the proper CJS, ESM, UMD, UMD minified bundles.

* `namespace pixi_tilemap`: Removed that namespace from each file. `index.ts` wraps all the exported classes at one place instead.

### CODE REVIEW

**Comment by SukantPal** [comment]
@ivanpopelyshev You should consider removing one of the `package-lock.json` or `yarn.lock` shrink-wrap files (or migrate to pnpm - I'll help you there).

**Comment by blurymind** [comment]
the umd build doesnt seem to work and looking at the code I am not sure if its wrapped at all.
You can test it at this branch with gdevelop if you like. Just swap mine out for yours.
https://github.com/4ian/GDevelop/pull/1901

it comes up as undefined when gdevelop loads it. Mine gets a bit further - its not undefined, but fails further down.

A successfully loading example of a umd pixi library in gdevelop is pixi-multistyle-text, which is used by the bbcode extension

**Comment by SukantPal** [comment]
@blurymind The UMD build is wrapped:

https://github.com/SukantPal/pixi-tilemap/blob/74e19e538982ec0a549242d9e22629ea24e2456e/dist/pixi-tilemap.umd.js#L12

I think I know what the problem is. The UMD build of `@pixi/display`, for example, is wrapped in `_pixi_display`. But the UMD build of `pixi.js` is wrapped in `PIXI` & doesn't expose `_pixi_display`.

**Comment by SukantPal** [comment]
@blurymind Can you try again?

**Comment by blurymind** [comment]
yes sure, thanks for helping me :)

**Comment by blurymind** [comment]
It gets a bit further now. The library is imported by gdevelop, but the moment I try to use it I get
 PIXI.tilemap.CompositeRectTileLayer

**Comment by SukantPal** [comment]
@blurymind I forgot to assign `PIXI.tilemap` to `_pixi_tilemap`. One sec.

**Comment by SukantPal** [comment]
Okay, try again :)

**Comment by blurymind** [comment]
This change seems to have regressed it. I get this now when trying to load the module
`ReferenceError: _pixi_tilemap is not defined
`

**Comment by SukantPal** [comment]
Ugh. I thought the name was `_pixi_tilemap`, but it should've been `pixi_tilemap`. I pushed a fix for this. Sorry for these silly mistakes.

**Comment by blurymind** [comment]
will this address the previous issue which is
`PIXI.tilemap.CompositeRectTileLayer is not a constructor`

I need  to debug this a bit more

**Comment by SukantPal** [comment]
https://github.com/SukantPal/pixi-tilemap/blob/695b63aab09152017d39df508f96438bb6e20327/dist/pixi-tilemap.umd.js#L953

It should be there. Can you `console.log(PIXI.tilemap)`?

**Comment by blurymind** [comment]
Ah interesting, now its loading fine, but I am getting a different error when trying to use it

```
Container.ts:428 Uncaught TypeError: Cannot read property 'transform' of null
    at t.Container.updateTransform (Container.ts:428)
    at t.Container.getLocalBounds (Container.ts:506)
    at t.get (Container.ts:669)
    at RenderedTileMapInstance.getDefaultWidth (D:\DEV\GD\GDevelop\newIDE\app\resources\GDJS\Runtime\Extensions\TileMap\JsExtension.js:494)
    at LayerRenderer.getInstanceWidth (LayerRenderer.js:92)
    at LayerRenderer._isInstanceVisible (LayerRenderer.js:178)
    at InitialInstanceJSFunctor.LayerRenderer.instancesRenderer.invoke (LayerRenderer.js:59)
    at 8152 (libGD.js?cache-buster=5.0.0-beta98-e240a7c80d1abab373f93f826c8ca5fa39b63774:51)
    at _emscripten_asm_const_iii (libGD.js?cache-buster=5.0.0-beta98-e240a7c80d1abab373f93f826c8ca5fa39b63774:51)
    at Array._B (libGD.js?cache-buster=5.0.0-beta98-e240a7c80d1abab373f93f826c8ca5fa39b63774:25)
    at Array.ib (libGD.js?cache-buster=5.0.0-beta98-e240a7c80d1abab373f93f826c8ca5fa39b63774:25)
    at hF (libGD.js?cache-buster=5.0.0-beta98-e240a7c80d1abab373f93f826c8ca5fa39b63774:25)
    at As (libGD.js?cache-buster=5.0.0-beta98-e240a7c80d1abab373f93f826c8ca5fa39b63774:25)
    at InitialInstancesContainer.IterateOverInstancesWithZOrdering.InitialInstancesContainer.IterateOverInstancesWithZOrdering [as iterateOverInstancesWithZOrdering] (libGD.js?cache-buster=5.0.0-beta98-e240a7c80d1abab373f93f826c8ca5fa39b63774:51)
    at LayerRenderer.render (LayerRenderer.js:204)
    at InstancesRenderer.render (index.js:117)
    at InstancesEditor._renderScene (index.js:728)
```

**Comment by blurymind** [comment]
I confirm i can log PIXI.tilemap, but some of the items in it come up with type errors

Capture

is this perhaps due to strict mode?

**Comment by ivanpopelyshev** [comment]
That's function-related stuff, its supposed to be like that

**Comment by SukantPal** [comment]
@blurymind Can you give me a test script using pixi-tilemap so I can debug this today evening?

**Comment by blurymind** [comment]
> @blurymind Can you give me a test script using pixi-tilemap so I can debug this today evening?

All I have at the moment is the PR branch getting it to work in gdevelop with an example json fileto use
https://github.com/4ian/GDevelop/pull/1901

This used to work with a normal module, but after gdevelop was ported to pixi5 we are now required to use umd modules.

My pr adds a new tilemap game object which should work in the IDE, but doesnt yet work when you playtest the game.
It is also possible there is an error somewhere in my extension, so I am looking into that as a potential issue too

**Comment by blurymind** [comment]
I believe the problem is still in pixi-tilemap because the error I get is
```
Container.ts:428 Uncaught TypeError: Cannot read property 'transform' of null
    at RectTileLayer.Container.updateTransform
```

**Comment by SukantPal** [comment]
@blurymind I would open a separate issue for that - with a minimal reproduction. @ivanpopelyshev would be the guy looking at that 😅

**Comment by blurymind** [comment]
Do we have any proof that pixi-tilemap works as a umd module in anything? :)

**Comment by SukantPal** [comment]
Since the codebase is cleaner now, I might be able to help you too there.

**Comment by SukantPal** [comment]
Up until now, there was no UMD module - so no. The error your talking about is a runtime error - not something related to the UMD build (as far as I can see).

**Comment by blurymind** [comment]
I have a feeling that this is something that comes from its umd nature or pixi5, but its hard to tell.
Btw you might be able to get a better testing ground by using it in this example project
https://github.com/Alan01252/pixi-tilemap-tutorial

**Comment by blurymind** [comment]
I made this as a testing ground
https://github.com/blurymind/pixi-tilemap-tutorial/tree/pixi-umd
feel free to fork and play. The module loads, but fails to work

It is also possible that some of the code still needs changing to work with pixi5

**Comment by blurymind** [comment]
I updated my demo project now to better test against pixi-tilemap as it is in dist on master for pixi 5.

The compiled version of the umd module does not work, the vanila version works fine.
You can comment one out and try with the other in the index.html to see.

To test on localhost you can use 
`npx http-server .`

**Comment by blurymind** [comment]
Have you managed to do some testing with the project I provided? Is there anything else I can do to help this PR? It's something we need to get pixi-tilemap working again in gdevelop and blocks my PR there atm

**Comment by SukantPal** [comment]
I have not yet, sorry. I’ve been working 8-9 hrs/day, 7 days/week for some time. Things to finish before closing a contract.

I might get time this weekend. Maybe @ivan can give a better guarantee.

Sent from my iPhone

On Aug 19, 2020, at 6:58 AM, Todor Imreorov <notifications@github.com> wrote:

﻿

Have you managed to do some testing with the project I provided? Is there anything else I can do to help this PR? It's something we need to get pixi-tilemap working again in gdevelop and blocks my PR there atm

**Comment by ivanpopelyshev** [comment]
I can accept other PR for now, if you are not sure about this one.

**Comment by SukantPal** [comment]
@ivan Both PRs give the same result. Mine just has more things than the UMD build.

Sent from my iPhone

On Aug 19, 2020, at 8:43 AM, Ivan Popelyshev <notifications@github.com> wrote:

﻿

I can accept other PR for now, if you are not sure about this one.

**Comment by SukantPal** [comment]
I think you could merge it, but don’t publish the package. We can fix the UMD.build stuff this weekend.

Sent from my iPhone

On Aug 19, 2020, at 8:43 AM, Ivan Popelyshev <notifications@github.com> wrote:

﻿

I can accept other PR for now, if you are not sure about this one.

**Comment by SukantPal** [comment]
@blurymind I made a fix, can you recheck?

**Comment by blurymind** [comment]
Thank you, I will give this a try after work :)

**Comment by blurymind** [comment]
@SukantPal that fixes it! The UMD build works in the example minimal project now!

**Comment by ivanpopelyshev** [comment]
ok, gonna re-publish it soon

**Comment by blurymind** [comment]
ah wait, there is something wrong with this

**Comment by blurymind** [comment]
sorry this might be a gdevelop related issue. It still fails in gdevelop unfortunately. I am trying to find out if its due to the module or gdevelop itself

**Comment by ivanpopelyshev** [comment]
Hell, whats wrong?

**Comment by SukantPal** [comment]
😆

**Comment by blurymind** [comment]
seems not like a real UMD module, it will work without issue in the
browser, but I see no "require" at all that would make it compatible with
"CommonJS" and so it's possibly not loaded properly in Electron.

**Comment by SukantPal** [comment]
Ah, I’ll see what’s going. You can file an issue so we can continue this thread there.

Sent from my iPhone

On Aug 20, 2020, at 7:39 PM, Todor Imreorov <notifications@github.com> wrote:

﻿

seems not like a real UMD module, it will work without issue in the
browser, but I see no "require" at all that would make it compatible with
"CommonJS" and so it's possibly not loaded properly in Electron.

**Comment by SukantPal** [comment]
Ah, I’ll see what’s going on. You can file an issue so we can continue this thread there.

Sent from my iPhone

On Aug 20, 2020, at 7:39 PM, Todor Imreorov <notifications@github.com> wrote:

﻿

seems not like a real UMD module, it will work without issue in the
browser, but I see no "require" at all that would make it compatible with
"CommonJS" and so it's possibly not loaded properly in Electron.

**Comment by blurymind** [comment]
@SukantPal opened a new ticket here
https://github.com/pixijs/pixi-tilemap/issues/97

**Pull request merged**
