### PR TITLE
Tile flipping

### PR DESCRIPTION
**Pull request by ekantor**
Implemented horizontal, vertical and diagonal [flipping](http://doc.mapeditor.org/en/stable/reference/tmx-map-format/?highlight=diagonal#tile-flipping)  of tiles, which is necessary when importing tilemaps from the popular [TILED editor](https://www.mapeditor.org/).
Works only with rectangular tiles.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
that's actually my speciality. I think i'll implement GroupD8 flips instead :)

**Comment by ivanpopelyshev** [comment]
https://github.com/pixijs/pixi.js/blob/dev/packages/math/src/GroupD8.js

**Comment by ekantor** [comment]
That would be great :)

**Comment by ivanpopelyshev** [comment]
Nono, i'll look at your code first.

**Comment by ivanpopelyshev** [comment]
Can you please make a demo for it? If you work with tiled it should be something that loads map from tiled.

**Comment by ekantor** [comment]
https://github.com/ekantor/pixi-tiled-test

**Comment by ivanpopelyshev** [comment]
i didnt have time yet, but i remember!

**Comment by ivanpopelyshev** [comment]
Oh right, I made my implementation of that thing. Just use `rotate` parameter

**Pull request closed without merging**
