### PR TITLE
Umd build

### PR DESCRIPTION
**Pull request by blurymind**
This adds the ability to build pixi-tilemap as a UMD module.
It should resolve 
https://github.com/pixijs/pixi-tilemap/issues/92

### CODE REVIEW

**Comment by blurymind** [comment]
please hold off from reviewing it for a bit. I need to better test this in gdevelop first.

**Comment by ivanpopelyshev** [comment]
I asked @SukantPal to help with adoption of same build system as in pixi-essentials (https://github.com/SukantPal/pixi-essentials/)

**Comment by SukantPal** [comment]
@blurymind I think this is more or less included in #95.

**Comment by blurymind** [comment]
ah thank you, I will give it a try and close this pr

**Comment by blurymind** [comment]
I will close this, as the other pr has the same goal anyway

**Pull request closed without merging**
